export const demoPage = `<!doctype html><html lang="zh-TW"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Peck Playground</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f4f2ed;color:#212622;font:16px/1.6 -apple-system,BlinkMacSystemFont,sans-serif}main{max-width:840px;margin:auto;padding:48px 40px}nav{display:flex;justify-content:space-between;align-items:center;margin-bottom:60px;font-size:14px}.wordmark{font-weight:600;letter-spacing:.1em}.tag{color:#657065}h1{font-size:40px;line-height:1.2;font-weight:500;letter-spacing:-.04em;margin:0 0 16px;max-width:500px}.intro{color:#677069;max-width:470px}section{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin:36px 0}.card{padding:24px;border:1px solid #d4d9d1;border-radius:16px;background:#fafbf7}h2{font-size:16px;font-weight:600;margin:0 0 12px}p{margin:0 0 20px}.small{font-size:14px;color:#677069}button{font:inherit;border:0;border-radius:10px;background:#253d30;color:#eef7f0;padding:12px 20px;cursor:pointer}button.secondary{background:#e3e9df;color:#253d30}input{width:100%;font:inherit;border:1px solid #c7cfc5;padding:10px 12px;border-radius:8px;margin-bottom:16px;background:white}footer{border-top:1px solid #d4d9d1;padding-top:24px;font-size:14px;color:#677069}#result{margin:16px 0 0;min-height:24px;font-size:14px}.number{font-size:24px;margin-bottom:12px}.note{padding:16px 20px;background:#e5eadd;border-radius:12px;font-size:14px}@media(max-width:600px){main{padding:32px 24px}nav{margin-bottom:36px}h1{font-size:32px}section{grid-template-columns:1fr}}
</style><main><nav><span class="wordmark">FIELDNOTES</span><span class="tag">Peck 範例專案</span></nav><h1 id="headline" data-source="electron/demo.ts">Make room for<br>your next idea.</h1><p class="intro">這是一個真的網頁。開啟 Peck 的「選取元件」，點選標題或按鈕，留下你想修改的地方。</p><section><article class="card"><h2>你的工作區</h2><p class="small">試著儲存，觀察 Console 和 Network 的紀錄。</p><label class="small" for="workspace-name">工作區名稱</label><input id="workspace-name" value="My next idea"/><button id="save-button" data-source="electron/demo.ts">儲存工作區</button><p id="result" role="status"></p></article><article class="card"><h2>一點小進展</h2><div class="number"><span id="count">3</span> 個想法</div><p class="small">這個計數會保留在目前分頁。把 Peck 放到背景，再打開試試。</p><button class="secondary" id="add-idea">新增想法</button></article></section><div class="note">先試試：選取上方標題，留言「標題改成中文，字小一點」。</div><footer>這是內建練習頁。也可以在網址列開啟你自己的開發站。</footer></main>
<script>
console.info('Playground ready', { project: 'fieldnotes' });
document.querySelector('#add-idea').addEventListener('click',()=>{const el=document.querySelector('#count');el.textContent=Number(el.textContent)+1;console.info('Idea added', {count:Number(el.textContent)})});
document.querySelector('#save-button').addEventListener('click',async()=>{const result=document.querySelector('#result');result.textContent='儲存中…';try{const response=await fetch('/demo/api/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:document.querySelector('input').value})});const data=await response.json();if(!response.ok)throw new Error(data.message);result.textContent='已儲存'}catch(error){console.error('Save failed:',error.message);result.textContent='範例錯誤：儲存失敗，請查看 Network。'}});
</script></html>`
